import { IUser } from '@/interfaces/user';

export const USERS: IUser[] = [
  {
    id: 1,
    name: 'Galadriel',
    race: 'Elfo (Noldor)',
    class: 'Rainha dos Elfos / Feiticeira',
    weapons: ['Magia', 'Nenya (um dos Três Anéis élficos)'],
    ally: 'Lothlórien, Sociedade do Anel',
  },
  {
    id: 2,
    name: 'Frodo Bolseiro',
    race: 'Hobbit',
    class: 'Aventureiro',
    weapons: ['Sting', 'Mithril'],
    ally: 'Sociedade do Anel',
  },
  {
    id: 3,
    name: 'Aragorn',
    race: 'Humano (Dúnedain)',
    class: 'Ranger / Rei',
    weapons: ['Andúril', 'Adaga'],
    ally: 'Gondor, Sociedade do Anel',
  },
  {
    id: 4,
    name: 'Gandalf',
    race: 'Maiar',
    class: 'Mago',
    weapons: ['Glamdring', 'Bastão'],
    ally: 'Sociedade do Anel',
  },
  {
    id: 5,
    name: 'Legolas',
    race: 'Elfo',
    class: 'Arqueiro',
    weapons: ['Arco élfico', 'Adagas'],
    ally: 'Sociedade do Anel',
  },
  {
    id: 6,
    name: 'Gimli',
    race: 'Anão',
    class: 'Guerreiro',
    weapons: ['Machado de batalha', 'Machado de mão'],
    ally: 'Sociedade do Anel',
  },
  {
    id: 7,
    name: 'Samwise Gamgee',
    race: 'Hobbit',
    class: 'Jardineiro / Aventureiro',
    weapons: ['Adaga élfica'],
    ally: 'Frodo Bolseiro',
  },
  {
    id: 8,
    name: 'Boromir',
    race: 'Humano',
    class: 'Guerreiro',
    weapons: ['Espada longa', 'Escudo'],
    ally: 'Gondor, Sociedade do Anel',
  },
  {
    id: 9,
    name: 'Saruman',
    race: 'Maiar',
    class: 'Mago',
    weapons: ['Magia', 'Bastão'],
    ally: 'Mordor (traidor dos magos)',
  },
  {
    id: 10,
    name: 'Sauron',
    race: 'Maiar',
    class: 'Senhor das Trevas',
    weapons: ['Anel do Poder'],
    ally: 'Mordor',
  },
  {
    id: 11,
    name: 'Gollum',
    race: 'Hobbit (corrompido)',
    class: 'Criatura',
    weapons: ['Astúcia', 'Dentes'],
    ally: 'Ele mesmo / O Anel',
  },
];
